import type { GlossEntry } from '../../lib/dictionary';
import food from './food.json';
import home from './home.json';
import work from './work.json';
import leisure from './leisure.json';
import travel from './travel.json';
import shopping from './shopping.json';
import school from './school.json';
import family from './family.json';
import health from './health.json';
import city from './city.json';
import daily from './daily.json';
import nature from './nature.json';

export interface TextQuestion {
  q: string;
  options: string[];
  answer: number;
}

export interface ReadingText {
  id: string;
  theme: string;
  level: 'A1' | 'A2';
  title: string;
  /** Klexikon article the text is adapted from (built-in texts), or a source label */
  source?: string;
  sourceUrl?: string;
  paragraphs: string[];
  glossary: Record<string, GlossEntry>;
  questions: TextQuestion[];
  /** generated by Claude on this device */
  generated?: boolean;
  createdAt?: number;
  /** extra exercises generated together with the text */
  fill?: { sentence: string; answer: string; hint_ru: string; wrong: string[] }[];
}

export const BUILTIN_TEXTS: ReadingText[] = (
  [food, home, work, leisure, travel, shopping, school, family, health, city, daily, nature] as unknown as ReadingText[][]
)
  .flat()
  .map((t) => ({ ...t, sourceUrl: t.source ? `https://klexikon.zum.de/wiki/${encodeURIComponent(t.source)}` : undefined }));

export function sourceLabel(t: ReadingText): string | null {
  if (t.generated) return t.source ? `По мотивам: ${t.source}` : 'Создано Claude';
  return t.source ? `По мотивам статьи Klexikon «${t.source}» (CC BY-SA 4.0)` : null;
}
